Feature/shopping cart phase 1
City-of-Helsinki/parking-permits-ui pull request #13
Opened 2021-05-20 08:57 UTC by amanpdyadav

* Add Shopping cart to stepper
* Add translations for shopping cart strings
* Add shoppingCart component
* Update vehicle selector to use data from redux
* Add reducers to handle cart properties actions
* Add actions for setting cart properties
* Add properties to PermitCartState

2021-05-21 09:56 UTC, mhieta requested changes
In general looks good, but added some comments regarding namings that should be still fixed before merging.

2021-05-21 09:56 UTC, mhieta commented on src/i18n/en.json
> +      "durationOfParkingCode": "Duration of parking code",
Is the **parking code** actually a **parking permit**? If so, we should probably use `parking permit` everywhere in the code.

2021-05-21 09:56 UTC, mhieta commented on src/i18n/fi.json
> +      "timeBeing": "Toistaiseksi voimassaoleva",
`timeBeing` --> `openEnded`

2021-05-21 09:56 UTC, mhieta commented on src/i18n/fi.json
> +      "temporary": "Määräaikainen",
`temporary`--> `fixedPeriod`

2021-05-21 09:56 UTC, mhieta commented on src/i18n/fi.json
> +      "parkingSignStartDate": "Pysäköintitunnuksen alkamispäivä",
`parkingSignStartDate` --> `parkingPermitStartDate`

2021-05-21 09:56 UTC, mhieta commented on src/i18n/fi.json
> +      "subTitle": "Ajonuovosi",
Typo: `Ajonuovosi` --> `Ajoneuvosi`

2021-05-21 09:56 UTC, mhieta commented on src/i18n/fi.json
>        "enterVehicleRegistrationNumber": "Syötå ajoneuvon rekisteritunnus",
Typo: `Syötå ajoneuvon rekisteritunnus` --> `Syötä ajoneuvon rekisteritunnus`

2021-05-21 11:42 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "subTitle": "Ajonuovosi",
Done

2021-05-21 11:42 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "parkingSignStartDate": "Pysäköintitunnuksen alkamispäivä",
Done

2021-05-21 11:43 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "temporary": "Määräaikainen",
Done

2021-05-21 11:43 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "timeBeing": "Toistaiseksi voimassaoleva",
Done

2021-05-21 11:43 UTC, amanpdyadav commented on src/i18n/en.json
> +      "durationOfParkingCode": "Duration of parking code",
Done

2021-05-21 11:44 UTC, amanpdyadav commented on src/i18n/fi.json
>        "enterVehicleRegistrationNumber": "Syötå ajoneuvon rekisteritunnus",
Done

2021-05-21 11:44 UTC, amanpdyadav commented on src/i18n/en.json
> +      "durationOfParkingCode": "Duration of parking code",
Done

2021-05-21 11:44 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "timeBeing": "Toistaiseksi voimassaoleva",
Done

2021-05-21 11:44 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "temporary": "Määräaikainen",
Done

2021-05-21 11:44 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "parkingSignStartDate": "Pysäköintitunnuksen alkamispäivä",
Done

2021-05-21 11:44 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "subTitle": "Ajonuovosi",
Done

2021-05-25 04:58 UTC, mhieta approved these changes
All Good now 💯

2021-05-25 05:47 UTC, merged