Styles update
City-of-Helsinki/parking-permits-ui pull request #25
Opened 2021-06-03 06:02 UTC by amanpdyadav

- Add translations for assistiveTexts
- Add assistive text for radio buttons
- Fix discount checkbox layout
- Update stepper theme to black
- Update footer theme to black
- Change buttons theme to black

Refs PV-144

2021-06-03 12:15 UTC, mhieta requested changes
One minor update. Looks good otherwise 👍

2021-06-03 12:15 UTC, mhieta commented on src/common/shoppingCart/ShoppingCart.tsx
> +  parkingDurationType = ParkingDurationType.OPEN_END,
I believe this type Enum name should be:
ParkingDurationType.**OPEN_ENDED**

2021-06-04 12:23 UTC, amanpdyadav commented on src/common/shoppingCart/ShoppingCart.tsx
> +  parkingDurationType = ParkingDurationType.OPEN_END,
Thanks for the review. Its updated.

2021-06-07 07:02 UTC, mhieta approved these changes
Good 💯

2021-06-07 07:07 UTC, merged