Front page implementation
City-of-Helsinki/parking-permits-ui pull request #7
Opened 2021-05-05 08:25 UTC by amanpdyadav

* Update user profile page to render name and address
* Add translations properties for texts
* Add address component
* Remove unnecessary types
* User translation instead of hardcoded string
* Add background to hero component
* Add social media icons to the footer of the page
* Rename parking-region-map to parking-zone-map
* Update front page to match the design
* Add feature reducers and actions
* Remove actions and reducers for zone and coordinates
* Add background to pages
* Allow front page access only by an authenticated user
* Move styles to assets folder
* Add marker icon
* Add classname package

2021-05-05 10:22 UTC, mhieta commented on src/i18n/fi.json
> +      "residentParkingZone": "Asukas pysäköintialue",
This would be one word: "Asukaspysäköintialue"

2021-05-05 10:23 UTC, mhieta commented on src/i18n/fi.json
> +      "title": "Hei Kaisa!",
As discussed earlier, this should be dynamic: "Hei <user_first_name>!"

2021-05-05 10:27 UTC, mhieta commented on src/common/navbar/Navbar.tsx
> +          />
We should have placeholder for swedish UI as well.

2021-05-05 10:29 UTC, mhieta commented on src/i18n/en.json
> +      "termsOfParkingCode": "Terms of the parking code",
Should this be terms of "parking permit"? Or is the "parking code" something different?

2021-05-05 10:33 UTC, mhieta requested changes
@amanpdyadav Added some comments, but in overall looks very nice! 👍

2021-05-06 07:15 UTC, amanpdyadav commented on src/i18n/en.json
> +      "termsOfParkingCode": "Terms of the parking code",
Done. Change to `Terms of the parking code`

2021-05-06 07:15 UTC, amanpdyadav commented on src/common/navbar/Navbar.tsx
> +          />
Done

2021-05-06 07:15 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "title": "Hei Kaisa!",
Done

2021-05-06 07:15 UTC, amanpdyadav commented on src/i18n/fi.json
> +      "residentParkingZone": "Asukas pysäköintialue",
Fixed

2021-05-06 08:01 UTC, mhieta approved these changes
Good, approved 💯

2021-05-06 08:16 UTC, merged